# Cargo.toml

[package]
name = "console-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
env_logger = "0"
log = "0"
parking_lot = "0"
structopt = "0"
tokio = { version = "1", features = ["full"] }
tokio-serial = "5.4.0-beta4"

[build-dependencies]
build-data = "0"

[profile.release]
lto = true
opt-level = 3 #default
# opt-level = 'z'  # Optimize for size.

# EOF
