# Cargo.toml

[package]
name = "net-serial-console"
version = "0.2.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "*"
chrono = "*"
env_logger = "*"
hyper = { version = "*", features = ["full"] }
log = "*"
once_cell = "*"
parking_lot = "*"
sailfish = "0.3.3"
structopt = "*"
tokio = { version = "*", features = ["full"] }
tokio-serial = "*"
tokio-util = { version = "*", features = ["full"] }

[build-dependencies]
build-data = "*"

[profile.release]
lto = true
opt-level = 3 #default
# opt-level = 'z'  # Optimize for size.

# EOF
