# Cargo.toml

[package]
name = "console-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
chrono = "0"
env_logger = "0"
log = "0"
# mio = "0"
parking_lot = "0"
serial = "0"
# serialport = "4"
# simple-error = "0"
structopt = "0"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
build-data = "0"

[profile.release]
lto = true
opt-level = 3 #default
# opt-level = 'z'  # Optimize for size.

# EOF
